[package]
name = "collaborative_filtering"
version = "0.1.0"
authors = ["Arpan-Kreeti <arpan.ghoshal@kreeti.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
